export type CanonEntityType =
  | "person"
  | "manifestation"
  | "place"
  | "work"
  | "faction"
  | "aeon"
  | "project"
  | "ambiguous";

export const HERTA_PERSON_PRIME = "herta.person.prime" as const;
export const HERTA_FORM_DOLL = "herta.form.doll" as const;
export const HERTA_PLACE_SPACE_STATION = "herta.place.space_station" as const;
export const HERTA_WORK_MANUSCRIPT = "herta.work.manuscript" as const;
export const HERTA_NAME_AMBIGUOUS = "herta.name.ambiguous" as const;

export type CanonEntityId = string;

export type CanonRelation =
  | "alias_of"
  | "manifestation_of"
  | "controls_or_uses"
  | "owns"
  | "member_of"
  | "associated_with"
  | "created"
  | "authored"
  | "speaker_in"
  | "appears_in";

export type CanonDocumentKind =
  | "character_profile"
  | "mission_dialogue"
  | "book_readable"
  | "world_lore"
  | "chronology"
  | "simulated_universe"
  | "unknown";

export interface CanonDocument {
  id: string;
  kind: CanonDocumentKind;
  title: string;
  path: string;
  url?: string;
  category?: string;
  sourceHash: string;
  sourceMtimeMs?: number;
  pageSubjectEntityId?: CanonEntityId;
  createdAt: string;
}

export interface CanonChunk {
  id: string;
  documentId: string;
  ordinal: number;
  sectionPath: string[];
  speaker?: string;
  speakerEntityId?: CanonEntityId;
  authorEntityId?: CanonEntityId;
  text: string;
  textHash: string;
  tokenEstimate: number;
  isDialogue: boolean;
  isHertaVoiceEvidence: boolean;
  isCanonFactCandidate: boolean;
  qualityScore: number;
}

export interface EntityMention {
  id: string;
  chunkId: string;
  surface: string;
  startOffset?: number;
  endOffset?: number;
  referentEntityId: CanonEntityId;
  embodimentEntityId?: CanonEntityId;
  speakerEntityId?: CanonEntityId;
  pageSubjectEntityId?: CanonEntityId;
  confidence: number;
  method: "deterministic" | "llm" | "human_review";
  rationale?: string;
}

export interface CanonEdge {
  id: string;
  sourceEntityId: CanonEntityId;
  relation: CanonRelation;
  targetEntityId: CanonEntityId;
  evidenceChunkId?: string; // null only for seed edges
  confidence: number;
  method: "deterministic" | "llm" | "human_review";
  rationale?: string;
}

export interface SeedEntity {
  id: CanonEntityId;
  type: CanonEntityType;
  canonicalName: string;
  description?: string;
  aliases: ReadonlyArray<{
    alias: string;
    lang?: "zh" | "en";
    priority?: number;
  }>;
}

export interface SeedEdge {
  sourceEntityId: CanonEntityId;
  relation: CanonRelation;
  targetEntityId: CanonEntityId;
  rationale?: string;
}

export type ClaimStatus = "active" | "obsolete" | "needs_review";
export type ClaimMethod = "deterministic" | "llm" | "human_review";

// Predicates the deterministic extractor may emit in Phase 3a.
// Other predicates may appear in later phases; this list is non-exhaustive.
export type ClaimPredicate =
  | "alias_of"
  | "manifestation_of"
  | "controls_or_uses"
  | "owns"
  | "member_of"
  | "associated_with"
  | "created"
  | "authored"
  | "speaker_in"
  | "appears_in"
  | "member_number";

export interface CanonClaim {
  id: string;
  subjectEntityId: CanonEntityId;
  predicate: ClaimPredicate | string;
  objectEntityId?: CanonEntityId;
  value?: string;
  qualifiersJson?: string;
  evidenceChunkIds: ReadonlyArray<string>;
  confidence: number;
  method: ClaimMethod;
  status: ClaimStatus;
  rationale?: string;
  createdAt: string;
  supersedesClaimId?: string;
}

// LLM-proposed claim shape, after JSON validation but before the resolver
// decides ADD / NOOP / MERGE / NEEDS_REVIEW. ProposedClaim does not yet have
// a stable id — the resolver assigns one when adding.
export interface ProposedClaim {
  subjectEntityId: CanonEntityId;
  predicate: string;
  objectEntityId?: CanonEntityId;
  value?: string;
  evidenceChunkIds: ReadonlyArray<string>;
  confidence: number;
  rationale?: string;
}

export type ClaimResolution =
  | { kind: "add" }
  | { kind: "noop"; existingClaimId: string }
  | {
      kind: "merge_evidence";
      existingClaimId: string;
      mergedChunkIds: ReadonlyArray<string>;
      newConfidence: number;
    }
  | {
      kind: "needs_review";
      conflictsWithClaimId?: string;
      reason: string;
    };

// Wiki page is a deterministic projection over a single entity's active claims,
// aliases, and voice evidence. Generated by Phase 3c's page builder; consumed
// by Phase 3d retrieval. Every relationship/attribute carries a claim_id; every
// claim carries (possibly empty) evidence_chunk_ids — a page paragraph that
// can't be traced back to a claim is a bug.

export interface WikiRelationship {
  claimId: string;
  predicate: string;
  targetEntityId: CanonEntityId;
  targetCanonicalName: string;
  confidence: number;
  method: ClaimMethod;
  evidenceChunkIds: ReadonlyArray<string>;
  rationale?: string;
}

export interface WikiAttribute {
  claimId: string;
  predicate: string;
  value: string;
  confidence: number;
  method: ClaimMethod;
  evidenceChunkIds: ReadonlyArray<string>;
  rationale?: string;
}

export interface WikiVoiceEvidence {
  chunkId: string;
  documentTitle: string;
  sectionPath: ReadonlyArray<string>;
  text: string;
}

export interface WikiUncertainClaim {
  claimId: string;
  predicate: string;
  targetEntityId?: CanonEntityId;
  targetCanonicalName?: string;
  value?: string;
  confidence: number;
  method: ClaimMethod;
  reason?: string;
}

export interface WikiPage {
  entityId: CanonEntityId;
  entityType: CanonEntityType;
  canonicalName: string;
  description?: string;
  aliases: ReadonlyArray<{
    alias: string;
    lang?: string;
    priority: number;
  }>;
  relationships: ReadonlyArray<WikiRelationship>;
  attributes: ReadonlyArray<WikiAttribute>;
  voiceEvidence: ReadonlyArray<WikiVoiceEvidence>;
  uncertainClaims: ReadonlyArray<WikiUncertainClaim>;
  claimIds: ReadonlyArray<string>;
  sourceChunkIds: ReadonlyArray<string>;
  generatedAt: string;
}

// VoiceProfile — Herta voice extraction (Phase 4 / Slice 3-6).
// See docs/superpowers/specs/2026-05-08-voice-profile-extraction-design.md.

export type AddresseeClass =
  | "player"
  | "other_named"
  | "self_narration"
  | "unknown";

export interface VoiceEvidenceStratum {
  chunkId: string;
  speakerEntityId: CanonEntityId;
  addresseeClass: AddresseeClass;
  addresseeEntityId?: CanonEntityId;
  classifierVersion: number;
  classifiedAt: string;
}

/**
 * An official-localization rendering of a canon chunk (schema v8, EN
 * interaction slice 2). Resolved through the aligned TextMaps — never
 * machine-translated. Joined against `voice_evidence_strata` so the CN
 * addressee analysis applies to the localized text unchanged.
 */
export interface ChunkTranslation {
  chunkId: string;
  /** BCP-47-ish short tag; "en" for now. */
  lang: string;
  /** The official localized line. */
  text: string;
  /** TextMap key witnessing the alignment. */
  textmapHash: string;
  /** How the CN chunk matched its TextMap line. */
  matchKind: "exact" | "normalized";
  alignedAt: string;
}

export interface VoiceFormOfAddress {
  phrase: string;
  evidenceChunkIds: ReadonlyArray<string>;
  contextHint?: string;
}

export interface VoiceToneInvariant {
  pattern: string;
  evidenceChunkIds: ReadonlyArray<string>;
}

export interface VoiceCodeSwitchTrigger {
  trigger: string;
  switchTo: "en" | "zh";
  evidenceChunkIds: ReadonlyArray<string>;
}

export interface VoiceMoodPattern {
  pattern: string;
  evidenceChunkIds: ReadonlyArray<string>;
}

export interface DefaultRegister {
  formsOfAddress: ReadonlyArray<VoiceFormOfAddress>;
  toneInvariants: ReadonlyArray<VoiceToneInvariant>;
  codeSwitchTriggers: ReadonlyArray<VoiceCodeSwitchTrigger>;
  moodModulators: {
    pleased?: ReadonlyArray<VoiceMoodPattern>;
    interested?: ReadonlyArray<VoiceMoodPattern>;
    annoyed?: ReadonlyArray<VoiceMoodPattern>;
  };
}

export type RelationshipRegisters = Readonly<
  Record<
    CanonEntityId,
    {
      register: DefaultRegister;
      evidenceChunkIds: ReadonlyArray<string>;
    }
  >
>;

export interface AntiPattern {
  pattern: string;
  rationale: string;
  evidenceAbsenceClaim: string;
}

export type StratumSource = "heuristic" | "llm" | "consensus" | "disagreement";

export type RegisterMode = "technical" | "casual" | "teaching" | "dramatic";

export type Mood = "pleased" | "interested" | "annoyed" | "severe" | "bored";

export interface StratumLlmExtensions {
  addresseeEntityIdLlm?: string;
  mood?: Mood;
  registerMode?: RegisterMode;
  groundedCitation?: string;
  confidence?: number;
  source: StratumSource;
  disagreementWithHeuristic: boolean;
  passAVerdictJson?: string;
  passBVerdictJson?: string;
}

export interface VoiceEvidenceStratumLlm
  extends VoiceEvidenceStratum,
    StratumLlmExtensions {}

export const VOICE_PROFILE_SCHEMA_VERSION = 2 as const;

export interface VoiceProfile {
  entityId: CanonEntityId;
  schemaVersion: number;
  defaultRegister: DefaultRegister;
  relationshipRegisters: RelationshipRegisters;
  /**
   * Self-narration register (book_readable text where Herta narrates in her
   * own voice, e.g. authored manuscripts). Stored on the row but, like
   * `relationshipRegisters`, NOT emitted at runtime — kept for offline
   * inspection and future use. Optional: populated only when R0 produced
   * `self_narration` strata and R2 validated entries against them.
   */
  selfNarration?: DefaultRegister;
  antiPatterns: ReadonlyArray<AntiPattern>;
  evidenceChunkIds: ReadonlyArray<string>;
  generatedAt: string;
  sourceRound: number;
}
